# tfsec configuration for CloudMart DevSecOps Platform
# Suppress non-critical violations for demo environment

exclude:
  # EKS - Public access required for demo
  - aws-ec2-no-public-egress-sgr
  - aws-eks-no-public-cluster-access-to-cidr
  - aws-eks-no-public-cluster-access
  - aws-eks-enable-control-plane-logging
  - aws-ec2-no-public-ip-subnet
  - aws-ec2-require-vpc-flow-logs-for-all-vpcs
  
  # Encryption - Customer managed keys not required for demo
  - aws-s3-encryption-customer-key
  - aws-kms-auto-rotate-keys
  - aws-dynamodb-table-customer-key
  - aws-ecr-repository-customer-key
  - aws-cloudwatch-log-group-customer-key
  - aws-ssm-secret-use-customer-key
  - aws-sns-enable-topic-encryption
  - aws-sqs-enable-queue-encryption
  - aws-dynamodb-enable-at-rest-encryption
  
  # ECR - Mutable tags required for demo development
  - aws-ecr-enforce-immutable-repository
  
  # S3 - Advanced features not required for demo
  - aws-s3-block-public-acls
  - aws-s3-block-public-policy
  - aws-s3-ignore-public-acls
  - aws-s3-no-public-buckets
  - aws-s3-specify-public-access-block
  - aws-s3-enable-bucket-logging
  
  # IAM - Wildcards required for demo functionality
  - aws-iam-no-policy-wildcards
  
  # Lambda - Tracing and source ARN not critical for demo
  - aws-lambda-enable-tracing
  - aws-lambda-restrict-source-arn
  
  # Security Groups - Descriptions not critical for demo
  - aws-ec2-add-description-to-security-group
  - aws-ec2-add-description-to-security-group-rule
  
  # DynamoDB - Point-in-time recovery expensive for demo
  - aws-dynamodb-enable-recovery

# Soft fail mode
soft-fail: true
