# Development Environment Configuration

environment: development
debug: true

# Application Configuration
app:
  name: cloudmart-dev
  port: 3000
  log_level: debug
  cors_enabled: true
  
# Database Configuration
database:
  dynamodb:
    region: us-east-1
    endpoint: http://localhost:8000  # Local DynamoDB
    tables:
      products: cloudmart-dev-products
      orders: cloudmart-dev-orders
      tickets: cloudmart-dev-tickets
      users: cloudmart-dev-users

# AI Services Configuration
ai:
  openai:
    model: gpt-3.5-turbo  # Use cheaper model for dev
    max_tokens: 500
    temperature: 0.7
  
  aws_bedrock:
    region: us-east-1
    model: anthropic.claude-instant-v1
  
  azure_ai:
    endpoint: https://cloudmart-dev.cognitiveservices.azure.com/
    api_version: "2023-05-15"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_port: 8080
  
# Security Configuration
security:
  jwt_expiry: 24h
  rate_limiting:
    enabled: true
    requests_per_minute: 100
  
  cors:
    allowed_origins:
      - http://localhost:3000
      - http://localhost:5173
    
# Feature Flags
features:
  ai_support: true
  analytics: false
  advanced_monitoring: false
