# Production Environment Configuration

environment: production
debug: false

# Application Configuration
app:
  name: cloudmart
  port: 5000
  log_level: info
  cors_enabled: true
  
# Database Configuration
database:
  dynamodb:
    region: us-east-1
    tables:
      products: cloudmart-products
      orders: cloudmart-orders
      tickets: cloudmart-tickets
      users: cloudmart-users

# AI Services Configuration
ai:
  openai:
    model: gpt-4
    max_tokens: 1000
    temperature: 0.5
  
  aws_bedrock:
    region: us-east-1
    model: anthropic.claude-3-sonnet-20240229-v1:0
  
  azure_ai:
    endpoint: https://cloudmart-prod.cognitiveservices.azure.com/
    api_version: "2023-05-15"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_port: 8080
  
# Security Configuration
security:
  jwt_expiry: 1h
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
  
  cors:
    allowed_origins:
      - https://cloudmart.example.com
      - https://admin.cloudmart.example.com
    
# Feature Flags
features:
  ai_support: true
  analytics: true
  advanced_monitoring: true

# Performance Configuration
performance:
  cache_ttl: 300
  connection_pool_size: 20
  request_timeout: 30000
  
# Scaling Configuration
scaling:
  min_replicas: 3
  max_replicas: 10
  target_cpu_utilization: 70
  target_memory_utilization: 80
